# -*- coding: utf-8 -*-
"""MM 02_Assignment_Colab_and_Binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LH5ORnxudoqckbQuKPPUdYCMUuGKJc31

<font color="red">__*PLEASE:* YOU MUST WRITE YOUR OWN CODE, YOU MAY NOT PASTE CODE FROM THE INTERNET, YOU MAY NOT SHARE CODE, YOU CAN DISCUSS WITH EACH OTHER. YOU CAN USE ANY RESOURCE ON THE INTERNET (although you should be able to find all answers in this notebook)__ </font>❗

<font color="red">**Also: As a first step, make sure you save your own copy of this notebook in colab.**</font>

<font color="red">**Directions:** Follow the directions to answer **all parts** of the 5 questions below.**</font>

<hr>

**This notebook will introduce you to the jupyter/colab environment and binary numbers.**

<hr>

I am a **text cell**! Double click on me to edit me. Then click off of me to let me *render*.
"""

# I am a code cell! Click to play to run me!
print('Hello World!')

"""### Exercise 1.
1. Create a new code cell below this one that prints out your full name using the print function.
"""

print('Marissa Mrkall')

"""### Exercise 2.

Create a new code cell below this one which:
* defines the function repeat_n, which
  * accepts two parameters, a str called s, and an integer n
  * uses a for loop to print the string s out n times
  * uses an if statement to deterine if n is even or odd, and prints out a message stating whether n is even or odd
  * returns a Boolean, True if n is odd, False if n is even.
* call this function with s = 'GO PURPLE EAGLES', and n = 3
* call this function with s = 'CIS 320 ROCKS!', with n = 4

After getting your code to work, hand-write it (by hand!) on a single page of paper and scan to pdf to submit in canvas.  

"""

def repeat_n(s, n):
  for i in range(n):
    print(s)

  if n % 2 == 0:
    print("n is even")
    return False
  else:
    print("n is odd")
    return True

repeat_n("GO PURPLE EAGLES", 3)
repeat_n("CIS 320 ROCKS!", 4)

"""### Binary numbers

We talked in class about how digital computers represent data using 1's and 0's or *binary*.

When integers (or more generally any data) are printed to the screen, it can be in a different base number system than the decimal (base 10) system we are familiar with.

**Base 10.** In the base 10 number system, we use the digits 0,1,2,3,4,5,6,7,8,9. A shift of one digit to the left means the digit represents 10 times more (ex: 2 and 20), two spaces to the left means multiplying by 100. Stated another way, the rightmost position of a base 10 integer represents the number of *ones* ($10^0$), the second from the right position represents the number of *tens* ($10^1$), the third from the right position represents the number of *hundreds* ($10^2$), and the $n^{th}$ position from the right represents the number of $10^ns$. For example, the number 234 means: four ones, three tens, and two hundreds.

**In base 2**, or binary, only the digits 0 and 1 are used. For example, 101 is a binary number representing the decimal number 5. (Note: we usually write binary numbers with a leading "0b" so that we don't confuse them with decimal numbers, i.e. 101 --> 0b101) The rightmost binary integer position represents the number of *ones* ($2^0$), the second from the right position represents the number of *twos* ($2^1$), the third position from the right represents the number of *fours* ($2^2$), the fourth position from the right represents the number of *eights* ($2^3$), and so on. Base 2 is especially important for computers since data is usually represented by elements that can be in one of only two states. For example, as mentioned earlier, the voltage on a wire can be either high or low, representing either a 1 or 0. Each digit in binary represents a ***bit*** of data. Eight bits of data are called a ***byte***.

**In base 16**, also called hexadecimal, the sixteen digits 0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F are used. When writing a number in hexadecimal, we usually write it with a leading "0x". For example 0x10 represents 16 in base ten. A shift of one to the left represents multiplying by 16, a shift of two to the left represents multiplying by 256 (i.e. 16*16), and shifting by $n$ spaces to the left represents multiplying by $16^n$).


|Decimal|Binary|Hexadecimal|
|---:|---:|---:|
|0|0|0|
|1|1|1|
|2|10|2|
|3|11|3|
|4|100|4|
|5|101|5|
|6|110|6|
|7|111|7|
|8|1000|8|
|9|1001|9|
|10|1010|A|
|11|1011|B|
|12|1100|C|
|13|1101|D|
|14|1110|E|
|15|1111|F|
|16|10000|10|
|17|10001|11|

Python provides some useful functions for converting numbers between bases:

    bin(<input int>)                 # convert a number TO a binary str
    hex(<input int>)                 # convert a number TO a hexadecimal str
    int(<input str>, <source base>)  # convert FROM a base other than 10
"""

# bin and hex
# The bin function converts an int (base 10) to a binary string
b = bin(13)
print('13 in binary is: ',b)
print('type(b)=', type(b))

# the hex function converts an int (base 10) into a base 16 string
h = hex(13)
print('13 in hexadecimal is: ',h)
print('type(h)=', type(h))

# int conversion
# the int function can convert from a different base back into an int
d = int(b,2) # binary to decimal
print('d=',d)
print('type(d)=', type(d))

d2 = int(h,16) # hexadecimal to decimal
print('d2=',d2)
print('type(d2)=', type(d2))

"""### Exercise 3

1. Without the use of a computer, make sure you understand how to convert between binary and decimal (For example, you should be able to write the following base 10 numbers in binary: 0, 7, 15, 255; and you should be able to write the following binary numbers in base 10: 10, 100, 101, 11111111, 100000000.) [There is nothing to turn in for this subquestion. ]

### Exercise 4
1. In a new code cell below, use the functions above to print out the decimal numbers 7, 2026, 64, 255 in binary.
1. In a new code cell below, use the functions above to print out the decimal representation of the binary number 1011010101110101.
"""

print(bin (7))
print(bin(2026))
print(bin(64))
print(bin(255))

print(int("1011010101110101", 2))

"""
<hr>

**SUBMISSION: Be sure to save this notebook, then download the .ipynb to your computer; and then submit (upload) the .ipynb file to the canvas assignment submission page. Don't forget to also upload the scanned hand written code as specified above (just the for the cell with the repeat_n function).**"""